language: android
sudo: required
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra
before_install:
    - chmod +x gradlew
    - wget http://services.gradle.org/distributions/gradle-2.10-bin.zip
    - unzip gradle-2.10-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.10
    - export PATH=$GRADLE_HOME/bin:$PATH

env:
  global:
    	- secure: beaeed0dcf5d6b3af6bbd481ae0a5d94cc4c4e87
install: gradle assemble
script: 
    - gradle check
after_success:
	- /initiate-publish.sh
	- /push-javadoc-to-gh-pages.sh
